name: aws-cicd
on:
  workflow_dispatch:
  workflow_call:
concurrency:
  group: "AWS"
  cancel-in-progress: true
jobs:
  deploy:
    name: AWS
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Configure dev AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::099267815798:role/github_oidc
          aws-region: ap-southeast-2

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install pipenv
        run: pip install pipenv

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install cdktf
        run: npm install --global cdktf-cli@latest

      - name: Install pip packages
        run: make install-dependencies

      - name: Perform unittest
        run: make unittest

      - name: Plan terraform configuration
        run: make aws-plan-all

      - name: Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: infrastructure/aws/cdktf.out/stacks/
          framework: terraform_plan
          skip_check: CKV_AWS_116,CKV_AWS_117,CKV_AWS_272,CKV2_AWS_57
        
      - name: Dev deployment
        run: make aws-deploy-all INFRA_ARGS=--auto-approve

      - name: Perform full test and check coverage
        run: make test

      - name: Conduct e2e testing
        run: make e2e

      - name: Configure prod AWS credentials
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::103417687554:role/github_oidc
          aws-region: ap-southeast-2

      - name: Prepare for production deployment
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: make clean
        
      - name: Production deployment
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: make aws-deploy-all INFRA_ARGS=--auto-approve

