name: cicd
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
concurrency:
  group: "cicd"
  cancel-in-progress: true
jobs:
  deploy:
    name: CI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      GRAFANA_API_KEY: ${{ secrets.GRAFANA_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Configure dev AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::099267815798:role/github_oidc
          aws-region: ap-southeast-2

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install pipenv
        run: pip install pipenv

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install cdktf
        run: npm install --global cdktf-cli@latest

      - name: Install pip packages
        run: make install-dependencies

      - name: Perform unittest
        run: make unittest

      - name: Synthesize terraform configuration template
        run: make build
        
      - name: Deploy deployment
        run: make deploy

      - name: Perform full test and check coverage
        run: make test

      - name: Conduct e2e testing
        run: make e2e

      - name: Configure prod AWS credentials
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::103417687554:role/github_oidc
          aws-region: ap-southeast-2
        
      - name: Production deployment
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: make deploy
        env:
          GRAFANA_API_KEY: ${{ secrets.GRAFANA_API_KEY_PROD }}
      
