name: cicd
on:
  workflow_dispatch:
  pull_request:
jobs:
  deploy:
    name: CI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::099267815798:role/github_oidc
          aws-region: ap-southeast-2

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install pipenv
        run: pip install pipenv

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install cdktf
        run: npm install --global cdktf-cli@latest

      - name: Install pip packages
        run: make local

      # - name: Synthesize aws cloudformation launch template
      #   run: make build-aws-cdk

      # - name: Test aws cdk
      #   run: make test-aws-cdk

      # - name: Deploy aws cdk
      #   run: make deploy-aws-cdk

      - name: Synthesize terraform configuration template
        run: make build-tf-cdk

      - name: Test terraform template
        run: make test-tf-cdk

      - name: Deploy terraform cdk
        run: make deploy-tf-cdk
      
      - name: Perform unittest
        run: make unittest

      - name: Perform integration test
        run: make integration-test

      - name: Perform Pytest
        run: make test

      - name: Conduct e2e testing
        run: make e2e
       
      # - name: Destroy terraform stack
      #   run: make destroy-tf-cdk
      
