name: gcp-cicd
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
concurrency:
  group: "GCP"
  cancel-in-progress: true
jobs:
  deploy:
    name: GCP
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install pipenv
        run: pip install pipenv

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install cdktf
        run: npm install --global cdktf-cli@latest

      - name: Install pip packages
        run: make install-dependencies

      - name: Synthesize terraform configuration template
        run: make gcp-synth

      - name: Deploy base infrastructure
        run: make gcp-deploy-base INFRA_ARGS=--auto-approve
      
      - name: Build & push docker image
        run: make gcp-build-image
      
      - name: Deploy main infrastructure
        run: make gcp-deploy-core INFRA_ARGS=--auto-approve

      # - name: Perform full test and check coverage
      #   run: make test

      # - name: Conduct e2e testing
      #   run: make e2e
